### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by LightDestory** [tunglamvghy/MSI-GE75-Raider-10SGS-hackintosh#1]
As the title says, can you add a license to the repository?

Please specify what we can do with this repository :)

Thanks, LightDestory

**Comment by tunglamvghy** [comment]
> As the title says, can you add a license to the repository?
> 
> Please specify what we can do with this repository :)
> 
> Thanks, LightDestory

You can use any parts of this repo without any cost. I upload it here for everyone.
